blog/core/views.py
from flask import render_template, request, Blueprint
from blog.models import Post


core = Blueprint('core', __name__)

@core.route('/')
def index():
    #get the page number from the url
    page = request.args.get('page', 1, type=int)

    #get the posts from the database in descending order
    blog_posts = Post.query.order_by(Post.date.desc()).paginate(page=page,
                                                            per_page=5)

    return render_template('index.html', blog_posts=blog_posts)


@core.route('/info')
def info():
    return render_template('info.html')

blog/posts/views.py
from blog.posts.forms import BlogPostForm
from flask import (render_template,url_for,flash,
                   redirect,request,Blueprint,abort)
from blog.app import db
from blog.models import Post
from flask_login import current_user,login_required


blog_posts = Blueprint('blog_posts',__name__)

#Create
@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = Post(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create.html',form=form)

#Blog Post (View)
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    post = Post.query.get_or_404(blog_post_id)

    return render_template('blog_post.html',title=post.title,
                           post=post)

#update blog post
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = Post.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text = form.text.data

        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index',blog_post_id=blog_post.id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create.html',title='Updating',form=form)

#delete blog post
@blog_posts.route('/<int:blog_post_id>/delete',methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = Post.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    return redirect(url_for('core.index'))

blog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required, login_user, logout_user
from blog.app import db
from blog.models import User,Post
from blog.users.forms import RegisterForm, LoginForm, UpdateUserForm
from blog.users.pictures import add_picture

users = Blueprint('users', __name__)

#register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(name = form.name.data,
                    email = form.email.data,
                    password = form.password.data,
                    )


        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


#logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

#login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():

        #.first() so the query doesn't return a list
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            if user.check_password(form.password.data) and user is not None:
                login_user(user)
                flash('Logged in successfully')

                #get the page the user was trying to access before logging in
                next = request.args.get('next')

                if next == None or next[0] != '/':
                    next = url_for('core.index')

                return redirect(next)

    return render_template('login.html', form=form)


#account
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()

    if form.validate_on_submit():

        #check if the user is uploading a new picture
        if form.picture.data:

            #add_picture in pictures.py
            name = current_user.name

            pic = add_picture(form.picture.data, name)

            #update the user's picture
            current_user.profile_image = pic

        #update the user's email and name
        current_user.name = form.name.data
        current_user.email = form.email.data
        db.session.commit()
        return redirect(url_for('users.account'))

    #if the user is not submitting the form, populate the form with the 
    #current user's data
    elif request.method == 'GET':
        form.email.data = current_user.email
        form.name.data = current_user.name

    #get the user's profile image
    profile_image = url_for('static', filename='profile_picture/'
                            + current_user.profile_image)


    return render_template('account.html',profile_image=profile_image,
                           form=form)


#user's list of posts
@users.route('/<name>')
def user_posts(name):

    #get the page number from the url
    page = request.args.get('page', 1, type=int)

    #get the user's posts
    #first_or_404() returns a 404 error if the user doesn't exist
    user = User.query.filter_by(name=name).first_or_404()

    #112 get the user's posts
    #113 order by date descending
    #114 paginate the posts
    blog_posts = Post.query.filter_by(author=user)\
        .order_by(Post.date.desc())\
        .paginate(page=page, per_page=5)


    return render_template('user_posts.html', blog_posts=blog_posts, user=user)


#test page
@users.route('/test')
def test():
    return render_template('test.html')

blog/templates/account.html
{% extends 'base.html' %}

{% block header %}

<div class="container">
    <h1>Account</h1>
    <img src="static/profile_picture/{{current_user.profile_image}}">
    <p>Name: {{ current_user.name }}</p>
    <p>Email: {{ current_user.email }}</p>
    </div>

<div class="container">

  <form method = "POST" action="" enctype="multipart/form-data">

    {{form.hidden_tag()}}

    <div class="form-group">

      {{form.email.label(class="form-control-label")}}

      {{form.email(class="form-control", placeholder="Email")}}

    </div>

    <div class="form-group">

      {{form.name.label(class="form-control-label")}}

      {{form.name(class="form-control", placeholder="First Name")}}

    </div>

    <div class="form-group">

      {{form.picture.label(class="form-control-label")}}

      {{form.picture(class="form-control", placeholder="Profile Picture")}}
    
    </div>

    <div class="form-group">

      {{form.submit(class="btn btn-primary")}}

    </div>


  </form>

</div>





{% endblock %}

blog/templates/base.html
<!DOCTYPE>
<html lang = "en">
    <head>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
         <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8"> 
    </head>
  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <div class="col-md-3 mb-2 mb-md-0">
        <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
          <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>
      </div>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{url_for('core.index')}}" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="{{url_for('core.info')}}" class="nav-link px-2 link-dark">Info</a></li>
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('blog_posts.create_post')}}" class="nav-link px-2 link-dark">Create Post</a></li>
        {% endif %}
      </ul>
    {% if current_user.is_authenticated %}

      <div class="col-md-3 text-end">
          <button type="button" class="btn btn-outline-primary me-2">
          <a  href="{{url_for('users.account')}}">Account</a>
          </button>
          <button type="button" class="btn btn-outline-primary me-2">
          <a href="{{url_for('users.logout')}}">Logout</a>
          </button>
      </div>

    {% else %}
      <div class="col-md-3 text-end">
          <button type="button" class="btn btn-outline-primary me-2">
            <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
          </button>
          <button type="button" class="btn btn-primary">
            <a class="nav-link" href="{{url_for('users.register')}}">Register</a>

          </button>
     </div>

    {% endif %}
    </header>
  </div>
    
{% block header  %}
{% endblock %}


<div class="container ">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
   <p class="col-md-4 mb-0 text-body-secondary">&copy;2023 Failed Blog</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
  </footer>
</div>



{% block footer  %}
{% endblock %}

blog/templates/blog_post.html
{% extends 'base.html' %}

{% block header %}

<div class="container">
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.name}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>

  {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




 <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

{% block footer %}

{% endblock %}

"{{url_for('blog_posts.delete_post', blog_post_id=post.id)}}"

blog/templates/create.html
{% extends 'base.html' %}

{% block header %}
    <h1>Create a new post</h1>
    <div class="container">
    <form class="form-groum" method="POST">
    
    {{form.hidden_tag()}}

    <div class="form-group">
        {{form.title.label(class="form-control-label")}}
        {{form.title(class="form-control")}}

    </div>

    <div class="form-group">
        {{form.text.label(class="form-control-label")}}
        {{ form.text(class_="form-control", style="height: 200px;") }}


    </div>

    <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
    </div>



    </form>
    </div>


{% endblock %}

{% block footer %}
{% endblock %}

blog/templates/index.html
<!DOCTYPE html>
{% extends 'base.html'  %}

<html lang='en'>
  <head>
    <title>Info Blog</title>
  </head>
  <body>
    {% block header  %}

     <div class="container">

    {# Go through each blog post #}
    {% for post in blog_posts.items %}

    <div class="card">

      <div class="card-body">


          <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', name=post.author.name) }}">Written By: {{ post.author.name }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>

    {% endblock %}

    {% block footer  %}
    {% endblock %}
  </body>

blog/templates/info.html
<!DOCTYPE html>

<html   lang = "en"> 
   <head> 
     <meta   charset = "utf-8"> 
     <title> Info </title> 
   </head> 
   <body>
  {% extends 'base.html' %}
  {% block header %}



<div class="position-absolute top-50 start-50 translate-middle">

  <div class = "container">
<div class="h-100 d-flex align-items-center justify-content-center">
     <h1> Info </h1> 
</div>
     <p> This is the info page. </p>

  </div>
</div>

  {% endblock %}
  {% block footer  %}
  
  
  {% endblock %}
   </body> 
 </html>

blog/templates/login.html
{% extends 'base.html' %}

{% block header  %}


<div class = "container">
<form method="POST">
  {{form.hidden_tag()}}

  <div class="form-group">
    {{form.email.label(class="control-label")}}
    {{form.email(class="form-control")}}
  </div>

  <div class="form-group">
    {{form.password.label(class="control-label")}}
    {{form.password(class="form-control")}}

  </div>

  <div class="form-group">
    {{form.submit(class="btn btn-primary")}}

  </div>
  </div>
    
{% endblock %}

{% block footer %}
{% endblock  %}

blog/templates/register.html
{% extends 'base.html' %}

{% block header  %}
<div class = "container">
<form method="POST">
  {{form.hidden_tag()}}

  <div class="form-group">
    {{form.name.label(class="control-label")}}
    {{form.name(class="form-control")}}
  </div>

  <div class="form-group">
    {{form.email.label(class="control-label")}}
    {{form.email(class="form-control")}}
  </div>

  <div class="form-group">
    {{form.password.label(class="control-label")}}
    {{form.password(class="form-control")}}

  </div>

  <div class="form-group">
    {{form.pass_confirm.label(class="control-label")}}
    {{form.pass_confirm(class="form-control")}}

  </div>

  <div class="form-group">
    {{form.submit(class="btn btn-primary")}}

  </div>
  </div>
{% endblock %}

{% block footer %}
{% endblock  %}

blog/templates/test.html
{% extends "base.html" %}

{% block header %}
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/user_posts.html
{% extends "base.html" %}
{% block header %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.name}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for post in blog_posts.items %}

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', name=post.author.name) }}">{{ post.author.name }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', name=user.name, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', name=user.name, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>




{% endblock %}



{% block footer %}
{% endblock %}